In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
movie=pd.read_csv("HollywoodMovies.csv")

In [4]:
movie.describe()

,RottenTomatoes,AudienceScore,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
count,913.000000,907.000000,949.000000,969.000000,945.000000,970.000000,876.000000,914.000000,897.000000,896.000000,895.000000,970.000000
mean,51.707558,61.271224,2495.246575,20.620826,8562.593651,68.162544,101.237419,169.009945,56.117168,384.620100,62.223575,2010.236082
std,26.821268,16.602457,1164.223356,25.338689,10645.135565,80.409969,155.987696,227.744380,53.755914,631.666012,159.713218,1.954840
min,0.000000,19.000000,1.000000,0.010000,28.000000,0.060000,0.000000,0.100000,0.000000,2.300000,0.160000,2007.000000
25%,28.000000,49.000000,2054.000000,5.300000,3528.000000,17.565000,16.667500,38.357500,20.000000,150.020000,19.505000,2009.000000
50%,52.000000,61.000000,2798.000000,13.150000,5983.000000,40.415000,46.655000,88.180000,35.000000,254.820000,34.610000,2010.000000
75%,75.000000,74.000000,3285.000000,26.200000,9790.000000,89.252500,111.908750,202.310000,75.000000,417.987500,58.375000,2012.000000
max,99.000000,96.000000,4468.000000,207.440000,147262.000000,760.500000,2021.000000,2781.500000,300.000000,10175.850000,3373.000000,2013.000000

In [5]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Movie             970 non-null    object
 1   LeadStudio        961 non-null    object
 2   RottenTomatoes    913 non-null    float64
 3   AudienceScore     907 non-null    float64
 4   Story             641 non-null    object
 5   Genre             691 non-null    object
 6   TheatersOpenWeek  949 non-null    float64
 7   OpeningWeekend    969 non-null    float64
 8   BOAvgOpenWeekend  945 non-null    float64
 9   DomesticGross     970 non-null    float64
 10  ForeignGross      876 non-null    float64
 11  WorldGross        914 non-null    float64
 12  Budget            897 non-null    float64
 13  Profitability     896 non-null    float64
 14  OpenProfit        895 non-null    float64
 15  Year              970 non-null    int64
dtypes: float64(11), int64(1), object(4)
memory usage: 121.4+ KB

In [13]:
np.percentile(movie.DomesticGross,[99][0])

372.0744999999993

In [15]:
uv=np.percentile(movie.DomesticGross,[99][0])

In [17]:
movie.DomesticGross[(movie.DomesticGross>2 *uv)]=2*uv

C:\Users\divya.sunil\AppData\Local\Temp\ipykernel_15780\2431893253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie.DomesticGross[(movie.DomesticGross>2 *uv)]=2*uv

In [18]:
movie[(movie.DomesticGross>uv)]

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
91,The Dark Knight,Warner Bros,94.0,96.0,Revenge,Thriller,4366.0,158.40,36283.0,534.860,469.70,1004.56,185.0,543.00,85.62,2008
239,Avatar,Fox,83.0,92.0,Metamorphosis,Action,3452.0,77.00,22313.0,744.149,2021.00,2781.50,237.0,1173.63,32.49,2009
240,Transformers: Revenge of the Fallen,Paramount,20.0,76.0,Revenge,Action,4234.0,109.00,25736.0,402.100,434.20,836.30,210.0,398.24,51.90,2009
499,Toy Story 3,Disney,99.0,91.0,Rescue,Animation,4028.0,110.30,27385.0,415.000,648.16,1063.16,200.0,531.58,55.15,2010
555,Harry Potter and the Deathly Hallows Part 2,Warner Bros,96.0,92.0,Rivalry,Fantasy,4375.0,169.19,38672.0,381.010,960.50,1341.51,125.0,1073.21,135.35,2011
726,Marvel's The Avengers,Buena Vista,92.0,91.0,NaN,NaN,4349.0,207.44,47698.0,623.360,895.24,1518.59,220.0,690.27,94.29,2012
778,The Dark Knight Rises,Warner Bros,88.0,90.0,NaN,NaN,4404.0,160.89,36532.0,448.140,636.30,1084.44,250.0,433.78,64.36,2012
786,The Hunger Games,Lionsgate,84.0,81.0,NaN,NaN,4137.0,152.54,36871.0,408.010,283.24,691.25,78.0,886.22,195.56,2012
823,Iron Man 3,Buena Vista,78.0,80.0,NaN,Action,4253.0,174.14,40946.0,409.010,806.43,1215.44,200.0,607.72,87.07,2013
825,THG: Catching Fire,Lionsgate,90.0,92.0,NaN,Action,4163.0,158.07,37971.0,420.020,435.87,855.90,130.0,658.38,121.59,2013

In [19]:
np.percentile(movie.DomesticGross,[1])[0]

1.32

In [20]:
lv=np.percentile(movie.DomesticGross,[1])[0]

In [21]:
movie[movie.DomesticGross<lv]

,Movie,LeadStudio,RottenTomatoes,AudienceScore,Story,Genre,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
383,Buried,Independent,86.0,63.0,Escape,Drama,11.0,0.103,9115.0,1.04,18.11,19.148,2.0,957.40,5.15,2010
542,Dylan Dog: Dead of Night,Independent,6.0,28.0,Monster Force,Horror,NaN,0.750,NaN,1.19,3.45,4.630,20.0,23.17,3.75,2011
571,Machine Gun Preacher,Lionsgate,29.0,71.0,Transformation,Action,NaN,0.050,NaN,0.54,0.57,1.100,30.0,3.68,0.17,2011
592,Red State,Independent,57.0,59.0,Escape,Horror,NaN,NaN,NaN,1.10,NaN,1.100,4.0,27.60,NaN,2011
612,The Beaver,Summit,62.0,57.0,Transformation,Drama,22.0,0.110,4890.0,0.97,5.40,6.370,21.0,30.33,0.52,2011
965,The Canyons,IFC,22.0,NaN,NaN,NaN,1.0,0.010,13351.0,0.06,0.14,0.190,NaN,77.21,NaN,2013
967,The English Teacher,Cinedigm Entertainment,42.0,NaN,NaN,NaN,2.0,0.010,3001.0,0.10,0.06,0.100,NaN,NaN,NaN,2013
968,John Dies at the End,Magnolia,61.0,53.0,NaN,NaN,1.0,0.010,12467.0,0.14,NaN,0.140,1.0,14.20,1.00,2013
969,Lovelace,Radius-TWC,55.0,37.0,NaN,Biography,118.0,0.180,1564.0,0.36,1.17,1.520,10.0,15.25,1.80,2013

In [23]:
movie.describe()

,RottenTomatoes,AudienceScore,TheatersOpenWeek,OpeningWeekend,BOAvgOpenWeekend,DomesticGross,ForeignGross,WorldGross,Budget,Profitability,OpenProfit,Year
count,913.000000,907.000000,949.000000,969.000000,945.000000,970.000000,876.000000,914.000000,897.000000,896.000000,895.000000,970.000000
mean,51.707558,61.271224,2495.246575,20.620826,8562.593651,68.145688,101.237419,169.009945,56.117168,384.620100,62.223575,2010.236082
std,26.821268,16.602457,1164.223356,25.338689,10645.135565,80.266266,155.987696,227.744380,53.755914,631.666012,159.713218,1.954840
min,0.000000,19.000000,1.000000,0.010000,28.000000,0.060000,0.000000,0.100000,0.000000,2.300000,0.160000,2007.000000
25%,28.000000,49.000000,2054.000000,5.300000,3528.000000,17.565000,16.667500,38.357500,20.000000,150.020000,19.505000,2009.000000
50%,52.000000,61.000000,2798.000000,13.150000,5983.000000,40.415000,46.655000,88.180000,35.000000,254.820000,34.610000,2010.000000
75%,75.000000,74.000000,3285.000000,26.200000,9790.000000,89.252500,111.908750,202.310000,75.000000,417.987500,58.375000,2012.000000
max,99.000000,96.000000,4468.000000,207.440000,147262.000000,744.149000,2021.000000,2781.500000,300.000000,10175.850000,3373.000000,2013.000000